/* iOS Clone Engine — web client (lane-scoped, mirrors lib/api/reviews.ts). */

export interface CloneFile {
  path: string;
  contents: string;
}
export interface CloneBlueprint {
  appName: string;
  bundleId: string;
  tagline: string;
  accentHex: string;
  primaryEntity: string;
  tabs: Array<{ title: string; symbol: string; kind: string; headline: string }>;
}
export interface CloneResult {
  appId: string;
  sourceTitle: string;
  projectName: string;
  blueprint: CloneBlueprint;
  files: CloneFile[];
  buildCommands: string[];
  aiGenerated: boolean;
  cached: boolean;
}

export async function cloneIos(appId: string, signal?: AbortSignal): Promise<CloneResult> {
  const res = await fetch(`/api/v1/clone/ios`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ appId }),
    signal,
  });
  if (!res.ok) throw new Error(`Clone failed (${res.status})`);
  const body = (await res.json()) as { data: CloneResult };
  return body.data;
}

/**
 * Build a dependency-free, self-extracting bash script that recreates every
 * project file via heredocs and runs xcodegen — one download, one `sh` run,
 * a buildable Xcode project. (Cloning needs Xcode locally, so a script the
 * user runs on their Mac is the honest delivery, not a browser-side build.)
 */
export function buildSetupScript(result: CloneResult): string {
  const lines: string[] = [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    `# ${result.blueprint.appName} — generated by the Kittie iOS Clone Engine`,
    `# Clone of "${result.sourceTitle}"`,
    `DIR="\${1:-${result.projectName}}"`,
    'mkdir -p "$DIR"',
    'cd "$DIR"',
    "",
  ];
  for (const f of result.files) {
    const dir = f.path.includes("/") ? f.path.slice(0, f.path.lastIndexOf("/")) : "";
    if (dir) lines.push(`mkdir -p "${dir}"`);
    // Quoted heredoc terminator => no shell expansion inside file contents.
    lines.push(`cat > "${f.path}" <<'KITTIE_EOF'`, f.contents.replace(/\r/g, ""), "KITTIE_EOF", "");
  }
  lines.push(
    'echo "Wrote project to $DIR"',
    "command -v xcodegen >/dev/null 2>&1 && xcodegen generate || echo 'Install xcodegen (brew install xcodegen), then run: xcodegen generate'",
    `echo "Open: open ${result.projectName}.xcodeproj"`,
    "",
  );
  return lines.join("\n");
}
