/**
 * Hot app ideas — LIVE data client.
 *
 * Ideas are real, traceable concepts generated by the autonomous pipeline
 * (server: idea-generator-service) which clones AppKittie's logic: it picks
 * today's rising-but-low-rated proven apps, mines their reviews for the
 * recurring gaps, and drafts a grounded concept + build blueprint into the
 * `app_ideas` store. This file just fetches + shapes those rows; there is no
 * static sample set — an empty store renders an honest empty/dormant state.
 */

const BASE = "/api/v1";

export type BlueprintTag = "backend" | "database" | "ai";

export interface AppIdea {
  id: string;
  slug: string | null;
  title: string;
  /** The concept prose (server: summary) — names the gap it fixes. */
  description: string;
  /** Category of the real source app this was mined from. */
  sourceCategory: string;
  /** What kind of product the idea itself is. */
  ideaCategory: string;
  /** Source-app review count (real provenance). */
  reviews: number;
  /** Source-app rating (real provenance) — low ratings are the signal. */
  rating: number | null;
  /** Epoch seconds the idea was generated. */
  createdAt: number | null;
  sourceAppId: string | null;
  /** Build-effort preview from the stored blueprint. */
  difficulty: string | null;
  timelineWeeks: number | null;
  blueprint: BlueprintTag[];
}

/** Status of the autonomous generator — drives the freshness stamp + gating. */
export interface IdeaGenerator {
  lastRunAt: number | null;
  lastGenerated: number;
  totalIdeas: number;
  latestIdeaAt: number | null;
  dormantReason: string | null;
}

export interface IdeasQuery {
  search?: string;
  sourceCategory?: string;
  ideaCategory?: string;
  blueprint?: BlueprintTag[];
  sort?: "created" | "reviews" | "rating";
  order?: "asc" | "desc";
  page?: number;
  pageSize?: number;
}

export interface IdeasPage {
  ideas: AppIdea[];
  total: number;
  page: number;
  pageSize: number;
  pageCount: number;
}

const BLUEPRINT_LABEL: Record<BlueprintTag, string> = {
  backend: "Needs backend",
  database: "Needs database",
  ai: "Needs AI",
};
export function blueprintLabel(tag: BlueprintTag): string {
  return BLUEPRINT_LABEL[tag];
}

/* ------------------------------------------------------------------ fetch */

interface RawCard {
  id: string;
  slug: string | null;
  title: string;
  summary: string | null;
  sourceCategory: string | null;
  ideaCategory: string | null;
  rating: number | null;
  reviewCount: number;
  needsBackend: boolean;
  needsDatabase: boolean;
  needsAi: boolean;
  difficulty: string | null;
  timelineWeeks: number | null;
  createdAt: number | null;
  sourceAppId: string | null;
}

function toIdea(r: RawCard): AppIdea {
  const blueprint: BlueprintTag[] = [];
  if (r.needsBackend) blueprint.push("backend");
  if (r.needsDatabase) blueprint.push("database");
  if (r.needsAi) blueprint.push("ai");
  return {
    id: r.id,
    slug: r.slug,
    title: r.title,
    description: r.summary ?? "",
    sourceCategory: r.sourceCategory ?? "Unknown",
    ideaCategory: r.ideaCategory ?? "App",
    reviews: r.reviewCount ?? 0,
    rating: r.rating,
    createdAt: r.createdAt,
    sourceAppId: r.sourceAppId,
    difficulty: r.difficulty,
    timelineWeeks: r.timelineWeeks,
    blueprint,
  };
}

export interface HotIdeasResult {
  available: boolean;
  ideas: AppIdea[];
  generator: IdeaGenerator | null;
}

export async function fetchHotIdeas(search?: string, signal?: AbortSignal): Promise<HotIdeasResult> {
  const q = search ? `?search=${encodeURIComponent(search)}` : "";
  const res = await fetch(`${BASE}/assist/ideas${q}`, { signal });
  if (!res.ok) return { available: false, ideas: [], generator: null };
  const body = (await res.json()) as {
    data?: { available?: boolean; ideas?: RawCard[]; generator?: IdeaGenerator };
  };
  const data = body.data ?? {};
  return {
    available: Boolean(data.available),
    ideas: (data.ideas ?? []).map(toIdea),
    generator: data.generator ?? null,
  };
}

/** Trigger an on-demand generation batch (same path as the daily sweep).
    Dormant no-op server-side when GEMINI_API_KEY is unset. */
export async function triggerIdeaGeneration(
  limit?: number,
): Promise<{ ran: boolean; generated: number; reason?: string }> {
  const res = await fetch(`${BASE}/assist/generate-ideas`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(limit ? { limit } : {}),
  });
  if (!res.ok) return { ran: false, generated: 0, reason: `Request failed (${res.status})` };
  return ((await res.json()) as { data: { ran: boolean; generated: number; reason?: string } }).data;
}

/* ----------------------------------------------- pure in-memory filter/sort */

/** Filter / sort / paginate over an already-fetched idea set (≤ a few
    hundred rows, so client-side is fine). */
export function queryIdeas(all: AppIdea[], q: IdeasQuery = {}): IdeasPage {
  const {
    search = "",
    sourceCategory = "",
    ideaCategory = "",
    blueprint = [],
    sort = "created",
    order = "desc",
    page = 1,
    pageSize = 12,
  } = q;

  const needle = search.trim().toLowerCase();
  let rows = all.filter((i) => {
    if (needle && !`${i.title} ${i.description}`.toLowerCase().includes(needle)) return false;
    if (sourceCategory && i.sourceCategory !== sourceCategory) return false;
    if (ideaCategory && i.ideaCategory !== ideaCategory) return false;
    if (blueprint.length && !blueprint.every((b) => i.blueprint.includes(b))) return false;
    return true;
  });

  const dir = order === "asc" ? 1 : -1;
  rows = rows.slice().sort((a, b) => {
    if (sort === "reviews") return (a.reviews - b.reviews) * dir;
    if (sort === "rating") return ((a.rating ?? 0) - (b.rating ?? 0)) * dir;
    return ((a.createdAt ?? 0) - (b.createdAt ?? 0)) * dir;
  });

  const total = rows.length;
  const pageCount = Math.max(1, Math.ceil(total / pageSize));
  const safePage = Math.min(Math.max(1, page), pageCount);
  const start = (safePage - 1) * pageSize;
  return {
    ideas: rows.slice(start, start + pageSize),
    total,
    page: safePage,
    pageSize,
    pageCount,
  };
}
