import { getIdeaRow, ideasTableExists, listIdeaRows, type IdeaRow } from "@kittie/db";

import { getDb } from "../lib/db.js";
import { generateText, seamStatus } from "./llm-seam.js";

/* ============================================================
   Idea → PRD bridge (PRD-additive-edge D11) — the additive delta
   beyond AppKittie's "Export as prompt": a full PRD + Claude-Code
   prompt pack assembled by TEMPLATE from a stored Hot idea, with
   optional one-call Gemini enrichment of the Problem/Solution
   prose when the seam is live. Template path costs $0 and always
   works; enrichment silently falls back on any failure.
   ============================================================ */

export interface IdeaSummary {
  id: string;
  slug: string | null;
  title: string;
  summary: string | null;
  category: string | null;
}

export async function listIdeas(
  search?: string,
  limit = 50,
): Promise<{ available: boolean; ideas: IdeaSummary[] }> {
  const db = getDb();
  if (!(await ideasTableExists(db))) return { available: false, ideas: [] };
  const rows = await listIdeaRows(db, { search, limit });
  return {
    available: true,
    ideas: rows.map((r) => ({
      id: r.id,
      slug: r.slug,
      title: r.title,
      summary: r.summary,
      category: r.ideaCategory ?? r.sourceCategory,
    })),
  };
}

/* ----------------------------------------------------- templating */

/** Pull a usable string/array out of the idea's blueprint JSON, whatever
    column names the parity pipeline chose. Never fabricates. */
function blueprintField(idea: IdeaRow, names: string[]): string | null {
  for (const n of names) {
    const v = idea.extra[n];
    if (typeof v === "string" && v.trim()) return v.trim();
    if (v != null && typeof v === "object") {
      try {
        return JSON.stringify(v, null, 2);
      } catch {
        /* skip */
      }
    }
  }
  // Some pipelines store one blueprint JSON blob.
  for (const n of ["blueprint", "blueprint_json", "build_blueprint"]) {
    const raw = idea.extra[n];
    if (typeof raw === "string" && raw.trim().startsWith("{")) {
      try {
        const obj = JSON.parse(raw) as Record<string, unknown>;
        for (const key of names) {
          const v = obj[key];
          if (typeof v === "string" && v.trim()) return v.trim();
          if (Array.isArray(v) && v.length > 0) return v.map((x) => `- ${String(x)}`).join("\n");
        }
      } catch {
        /* not JSON — skip */
      }
    }
  }
  return null;
}

function section(heading: string, body: string | null): string {
  return body ? `## ${heading}\n\n${body}\n\n` : "";
}

function buildTemplatePrd(idea: IdeaRow): string {
  const difficulty = blueprintField(idea, ["difficulty", "difficulty_reasoning", "difficultyReasoning"]);
  const timeline = blueprintField(idea, ["timeline", "estimated_timeline", "estimatedTimeline"]);
  const requirements = blueprintField(idea, ["requirements", "needs"]);
  const mvp = blueprintField(idea, ["mvp_features", "mvpFeatures", "mvp_scope", "mvpScope", "mvp"]);
  const keyFeatures = blueprintField(idea, ["key_features", "keyFeatures", "features"]);
  const v2 = blueprintField(idea, ["v2_features", "v2Features", "future_features"]);
  const architecture = blueprintField(idea, ["architecture", "tech_architecture"]);
  const stack = blueprintField(idea, ["tech_stack", "techStack", "stack"]);
  const services = blueprintField(idea, ["third_party_services", "thirdPartyServices", "services"]);

  return (
    `# PRD — ${idea.title}\n\n` +
    section("Problem", idea.summary) +
    section(
      "Solution",
      `${idea.title}${idea.ideaCategory ? ` — a ${idea.ideaCategory} product` : ""}. Derived from a real fast-growing app's gap (source category: ${idea.sourceCategory ?? "unknown"}).`,
    ) +
    section("Difficulty", difficulty) +
    section("Timeline", timeline) +
    section("Requirements", requirements) +
    section("MVP scope", mvp) +
    section("Key features", keyFeatures) +
    section("V2 candidates", v2) +
    section("Architecture", architecture) +
    section("Tech stack", stack) +
    section("Third-party services", services) +
    `---\n\n*Generated by Kittie's Idea → PRD bridge from a stored Hot idea. Sections without stored blueprint data are omitted rather than invented.*\n`
  );
}

function buildPromptPack(prd: string, title: string): string {
  return (
    `You are Claude Code. Build "${title}" from the PRD below.\n\n` +
    `Working agreement:\n` +
    `1. Scaffold the repo first (choose the stack from the PRD; pnpm if Node).\n` +
    `2. Build the MVP scope ONLY — defer V2 candidates.\n` +
    `3. Ship vertical slices: each commit is runnable and demoable.\n` +
    `4. Write tests for core logic as you go; typecheck clean before done.\n` +
    `5. When the PRD is ambiguous, choose the simplest interpretation and note it in the README.\n\n` +
    `--- PRD ---\n\n${prd}`
  );
}

/* ------------------------------------------------------ assembly */

export interface PrdResult {
  available: boolean;
  enriched: boolean;
  markdown?: string;
  promptPack?: string;
}

export async function buildPrd(ideaId: string): Promise<PrdResult> {
  const idea = await getIdeaRow(getDb(), ideaId);
  if (!idea) return { available: false, enriched: false };

  let markdown = buildTemplatePrd(idea);
  let enriched = false;

  // Frugal seam use (free key is heavily quota-limited): one call, only the
  // Problem/Solution prose, hard fallback to the template on any failure.
  if (seamStatus().enabled) {
    const sharpened = await generateText(
      `Rewrite ONLY the "Problem" and "Solution" sections of this PRD to be sharper and more concrete (2-4 sentences each). Keep every other section verbatim. Return the FULL markdown document.\n\n${markdown}`,
      { maxOutputTokens: 2048 },
    );
    if (sharpened && sharpened.includes("# PRD")) {
      markdown = sharpened;
      enriched = true;
    }
  }

  return {
    available: true,
    enriched,
    markdown,
    promptPack: buildPromptPack(markdown, idea.title),
  };
}
