import type { AppBlueprint, BlueprintTab, GeneratedFile } from "./types.js";

/* ============================================================
   Stage 2 — deterministic SwiftUI codegen.

   Given a validated blueprint, emit a complete xcodegen project. Everything
   here is pure string templating over a fixed, iOS-17-safe SwiftUI vocabulary,
   so the output ALWAYS compiles. The model's content only flows in as escaped
   string literals and a clamped enum (TabKind / SF symbol).
   ============================================================ */

/** Escape a JS string for safe embedding inside a Swift "..." literal. */
function sw(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, " ")
    .replace(/\t/g, " ");
}

/** PascalCase, ASCII-letters-only Swift identifier; always starts with a letter. */
function pascal(s: string, fallback = "Clone"): string {
  const cleaned = (s.match(/[A-Za-z0-9]+/g) ?? [])
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  const id = cleaned.replace(/^[0-9]+/, "");
  return id || fallback;
}

/** Project / app type prefix derived from the brand name. */
export function projectNameFor(b: AppBlueprint): string {
  return pascal(b.appName, "CloneApp");
}

/** Unique Swift type name per tab (deduped by index). */
function tabTypeName(tab: BlueprintTab, i: number): string {
  return `${pascal(tab.title, `Screen${i + 1}`)}Screen${i}`;
}

/** "#RRGGBB" -> 0xRRGGBB literal. */
function hexLiteral(hex: string): string {
  return `0x${hex.replace("#", "").toUpperCase()}`;
}

/* ---- file templates ---------------------------------------------------- */

function projectYml(b: AppBlueprint, projectName: string): string {
  return `name: ${projectName}
options:
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
targets:
  ${projectName}:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${b.bundleId}
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.0"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: "${b.appName}"
`;
}

function themeSwift(b: AppBlueprint): string {
  return `import SwiftUI

// Generated by the Kittie iOS Clone Engine.
extension Color {
    init(hex: UInt) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255,
            opacity: 1
        )
    }
}

enum Theme {
    static let accent = Color(hex: ${hexLiteral(b.accentHex)})
    static let surface = Color(.secondarySystemBackground)
    static let bg = Color(.systemBackground)
}
`;
}

function modelSwift(b: AppBlueprint): string {
  const arrays = b.tabs
    .map((tab, i) => {
      const items = tab.items
        .map(
          (it) =>
            `        Entry(title: "${sw(it.title)}", subtitle: "${sw(it.subtitle)}", detail: "${sw(it.detail)}")`,
        )
        .join(",\n");
      return `    static let tab${i}: [Entry] = [\n${items}\n    ]`;
    })
    .join("\n\n");
  return `import Foundation

// The single content model the cloned ${sw(b.primaryEntity)} app revolves around.
struct Entry: Identifiable, Hashable {
    let id = UUID()
    let title: String
    let subtitle: String
    let detail: String
}

enum SampleData {
${arrays}
}
`;
}

function componentsSwift(): string {
  return `import SwiftUI

// Reusable presentation pieces shared by every generated screen.

struct ScreenHeader: View {
    let headline: String
    let subhead: String
    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(headline).font(.largeTitle.bold())
            if !subhead.isEmpty {
                Text(subhead).font(.subheadline).foregroundStyle(.secondary)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(.horizontal)
        .padding(.top, 8)
    }
}

struct EntryRow: View {
    let entry: Entry
    var body: some View {
        HStack(spacing: 12) {
            RoundedRectangle(cornerRadius: 10)
                .fill(Theme.accent.opacity(0.18))
                .frame(width: 44, height: 44)
                .overlay(Image(systemName: "circle.fill").font(.caption).foregroundStyle(Theme.accent))
            VStack(alignment: .leading, spacing: 2) {
                Text(entry.title).font(.body.weight(.semibold))
                if !entry.subtitle.isEmpty {
                    Text(entry.subtitle).font(.caption).foregroundStyle(.secondary)
                }
            }
            Spacer()
            if !entry.detail.isEmpty {
                Text(entry.detail).font(.caption.weight(.medium)).foregroundStyle(Theme.accent)
            }
        }
        .padding(.vertical, 4)
    }
}

struct EntryCard: View {
    let entry: Entry
    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            RoundedRectangle(cornerRadius: 16)
                .fill(LinearGradient(colors: [Theme.accent, Theme.accent.opacity(0.6)],
                                     startPoint: .topLeading, endPoint: .bottomTrailing))
                .frame(height: 140)
                .overlay(
                    Text(entry.detail).font(.headline).foregroundStyle(.white)
                        .padding(12).frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .bottomTrailing)
                )
            Text(entry.title).font(.headline)
            if !entry.subtitle.isEmpty {
                Text(entry.subtitle).font(.subheadline).foregroundStyle(.secondary)
            }
        }
        .padding()
        .background(Theme.surface)
        .clipShape(RoundedRectangle(cornerRadius: 20))
    }
}

struct EntryTile: View {
    let entry: Entry
    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            RoundedRectangle(cornerRadius: 14)
                .fill(Theme.accent.opacity(0.22))
                .aspectRatio(1, contentMode: .fit)
                .overlay(Text(entry.detail).font(.caption.bold()).foregroundStyle(Theme.accent).padding(8),
                         alignment: .bottomLeading)
            Text(entry.title).font(.subheadline.weight(.semibold)).lineLimit(1)
            if !entry.subtitle.isEmpty {
                Text(entry.subtitle).font(.caption2).foregroundStyle(.secondary).lineLimit(1)
            }
        }
    }
}
`;
}

function screenBody(tab: BlueprintTab): string {
  switch (tab.kind) {
    case "feed":
      return `        ScrollView {
            ScreenHeader(headline: "${sw(tab.headline)}", subhead: "${sw(tab.subhead)}")
            LazyVStack(spacing: 16) {
                ForEach(items) { EntryCard(entry: $0) }
            }
            .padding()
        }`;
    case "grid":
      return `        ScrollView {
            ScreenHeader(headline: "${sw(tab.headline)}", subhead: "${sw(tab.subhead)}")
            LazyVGrid(columns: [GridItem(.flexible(), spacing: 12), GridItem(.flexible(), spacing: 12)], spacing: 12) {
                ForEach(items) { EntryTile(entry: $0) }
            }
            .padding()
        }`;
    case "form":
      return `        ScrollView {
            ScreenHeader(headline: "${sw(tab.headline)}", subhead: "${sw(tab.subhead)}")
            VStack(spacing: 14) {
                TextField("Title", text: $draftTitle)
                    .textFieldStyle(.roundedBorder)
                TextField("Notes", text: $draftNotes, axis: .vertical)
                    .lineLimit(3, reservesSpace: true)
                    .textFieldStyle(.roundedBorder)
                Button {
                    // demo action
                } label: {
                    Text("Add").frame(maxWidth: .infinity)
                }
                .buttonStyle(.borderedProminent)
                .tint(Theme.accent)
                Divider().padding(.vertical, 4)
                ForEach(items) { EntryRow(entry: $0) }
            }
            .padding()
        }`;
    case "profile":
      return `        ScrollView {
            VStack(spacing: 16) {
                Circle().fill(Theme.accent.opacity(0.25))
                    .frame(width: 92, height: 92)
                    .overlay(Image(systemName: "person.fill").font(.largeTitle).foregroundStyle(Theme.accent))
                    .padding(.top, 12)
                Text("${sw(tab.headline)}").font(.title2.bold())
                Text("${sw(tab.subhead)}").font(.subheadline).foregroundStyle(.secondary)
                VStack(spacing: 0) {
                    ForEach(items) { entry in
                        EntryRow(entry: entry)
                        if entry.id != items.last?.id { Divider() }
                    }
                }
                .padding()
                .background(Theme.surface)
                .clipShape(RoundedRectangle(cornerRadius: 18))
                .padding(.horizontal)
            }
        }`;
    default: // list
      return `        List(items) { EntryRow(entry: $0) }
            .listStyle(.plain)
            .safeAreaInset(edge: .top) {
                ScreenHeader(headline: "${sw(tab.headline)}", subhead: "${sw(tab.subhead)}")
                    .background(Theme.bg)
            }`;
  }
}

function screenSwift(tab: BlueprintTab, i: number, typeName: string): string {
  const needsFormState = tab.kind === "form";
  const state = needsFormState
    ? `    @State private var draftTitle = ""\n    @State private var draftNotes = ""\n`
    : "";
  return `import SwiftUI

struct ${typeName}: View {
    private let items = SampleData.tab${i}
${state}
    var body: some View {
        NavigationStack {
${screenBody(tab)}
                .navigationTitle("${sw(tab.title)}")
                .navigationBarTitleDisplayMode(.inline)
        }
    }
}
`;
}

function rootViewSwift(b: AppBlueprint, typeNames: string[]): string {
  const tabs = b.tabs
    .map(
      (tab, i) => `            ${typeNames[i]}()
                .tabItem { Label("${sw(tab.title)}", systemImage: "${tab.symbol}") }`,
    )
    .join("\n");
  return `import SwiftUI

struct RootView: View {
    var body: some View {
        TabView {
${tabs}
        }
        .tint(Theme.accent)
    }
}
`;
}

function appSwift(b: AppBlueprint, projectName: string): string {
  return `import SwiftUI

// ${b.appName} — ${b.tagline}
// A clone scaffold generated by the Kittie iOS Clone Engine.
@main
struct ${projectName}App: App {
    var body: some Scene {
        WindowGroup {
            RootView()
        }
    }
}
`;
}

function readme(b: AppBlueprint, projectName: string): string {
  return `# ${b.appName}

> ${b.tagline}

Generated by the **Kittie iOS Clone Engine** — a SwiftUI clone scaffold of a
trending App Store app. Core entity: **${b.primaryEntity}**.

## Screens
${b.tabs.map((t) => `- **${t.title}** (${t.kind}) — ${t.headline}`).join("\n")}

## Build & run

\`\`\`sh
xcodegen generate
open ${projectName}.xcodeproj
# or, headless on a booted simulator:
xcodebuild -project ${projectName}.xcodeproj -scheme ${projectName} \\
  -destination 'generic/platform=iOS Simulator' build
\`\`\`

Accent color: \`${b.accentHex}\`.  Bundle id: \`${b.bundleId}\`.
`;
}

/** Render a validated blueprint into a complete xcodegen project. */
export function generateProject(b: AppBlueprint): { projectName: string; files: GeneratedFile[] } {
  const projectName = projectNameFor(b);
  const typeNames = b.tabs.map((t, i) => tabTypeName(t, i));
  const files: GeneratedFile[] = [
    { path: "project.yml", contents: projectYml(b, projectName) },
    { path: "README.md", contents: readme(b, projectName) },
    { path: "Sources/App.swift", contents: appSwift(b, projectName) },
    { path: "Sources/Theme.swift", contents: themeSwift(b) },
    { path: "Sources/Components.swift", contents: componentsSwift() },
    { path: "Sources/Models.swift", contents: modelSwift(b) },
    { path: "Sources/RootView.swift", contents: rootViewSwift(b, typeNames) },
    ...b.tabs.map((tab, i) => {
      const tn = typeNames[i] ?? tabTypeName(tab, i);
      return { path: `Sources/${tn}.swift`, contents: screenSwift(tab, i, tn) };
    }),
  ];
  return { projectName, files };
}
