import type { AppBlueprint, BlueprintTab, GeneratedFile } from "./types.js";

/* ============================================================
   Stage 2 — deterministic SwiftUI codegen.

   Given a validated blueprint, emit a complete xcodegen project. Everything
   here is pure string templating over a fixed, iOS-17-safe SwiftUI vocabulary,
   so the output ALWAYS compiles. The model's content only flows in as escaped
   string literals and a clamped enum (TabKind / SF symbol).
   ============================================================ */

/** Escape a JS string for safe embedding inside a Swift "..." literal. */
function sw(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, " ")
    .replace(/\t/g, " ");
}

/** PascalCase, ASCII-letters-only Swift identifier; always starts with a letter. */
function pascal(s: string, fallback = "Clone"): string {
  const cleaned = (s.match(/[A-Za-z0-9]+/g) ?? [])
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  const id = cleaned.replace(/^[0-9]+/, "");
  return id || fallback;
}

/** Project / app type prefix derived from the brand name. */
export function projectNameFor(b: AppBlueprint): string {
  return pascal(b.appName, "CloneApp");
}

/** Unique Swift type name per tab (deduped by index). */
function tabTypeName(tab: BlueprintTab, i: number): string {
  return `${pascal(tab.title, `Screen${i + 1}`)}Screen${i}`;
}

/** "#RRGGBB" -> 0xRRGGBB literal. */
function hexLiteral(hex: string): string {
  return `0x${hex.replace("#", "").toUpperCase()}`;
}

/* ---- file templates ---------------------------------------------------- */

function projectYml(b: AppBlueprint, projectName: string): string {
  return `name: ${projectName}
options:
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
targets:
  ${projectName}:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${b.bundleId}
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.0"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: "${b.appName}"
`;
}

function themeSwift(b: AppBlueprint): string {
  return `import SwiftUI

// Generated by the Kittie iOS Clone Engine.
extension Color {
    init(hex: UInt) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255,
            opacity: 1
        )
    }
}

enum Theme {
    static let accent = Color(hex: ${hexLiteral(b.accentHex)})
    static let surface = Color(.secondarySystemBackground)
    static let bg = Color(.systemBackground)
}
`;
}

function modelSwift(b: AppBlueprint): string {
  const arrays = b.tabs
    .map((tab, i) => {
      const items = tab.items
        .map(
          (it) =>
            `        Entry(title: "${sw(it.title)}", subtitle: "${sw(it.subtitle)}", detail: "${sw(it.detail)}")`,
        )
        .join(",\n");
      return `    static let tab${i}: [Entry] = [\n${items}\n    ]`;
    })
    .join("\n\n");
  return `import Foundation

// The single content model the cloned ${sw(b.primaryEntity)} app revolves around.
struct Entry: Identifiable, Hashable {
    let id = UUID()
    let title: String
    let subtitle: String
    let detail: String

    /// "8/12 days" or "7 of 10" -> 0.58; nil when the detail isn't a ratio.
    var progress: Double? {
        let parts = detail
            .replacingOccurrences(of: " of ", with: "/")
            .split(separator: "/")
        guard parts.count == 2 else { return nil }
        let n = Double(parts[0].filter { $0.isNumber || $0 == "." })
        let d = Double(parts[1].filter { $0.isNumber || $0 == "." })
        guard let n, let d, d > 0, n <= d else { return nil }
        return n / d
    }
}

enum SampleData {
${arrays}
}
`;
}

function componentsSwift(): string {
  return `import SwiftUI

// Reusable presentation pieces shared by every generated screen.

struct ScreenHeader: View {
    let headline: String
    let subhead: String
    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(headline).font(.largeTitle.bold())
            if !subhead.isEmpty {
                Text(subhead).font(.subheadline).foregroundStyle(.secondary)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(.horizontal)
        .padding(.top, 8)
    }
}

/// Circular progress, Apple-Fitness style. Falls back to an icon disc.
struct ProgressRing: View {
    let value: Double
    var size: CGFloat = 40
    var body: some View {
        ZStack {
            Circle().stroke(Theme.accent.opacity(0.18), lineWidth: 4.5)
            Circle()
                .trim(from: 0, to: value)
                .stroke(Theme.accent, style: StrokeStyle(lineWidth: 4.5, lineCap: .round))
                .rotationEffect(.degrees(-90))
            Text("\\(Int(value * 100))")
                .font(.system(size: size * 0.28, weight: .bold, design: .rounded))
        }
        .frame(width: size, height: size)
    }
}

struct IconDisc: View {
    let symbol: String
    var size: CGFloat = 40
    var body: some View {
        RoundedRectangle(cornerRadius: size * 0.28)
            .fill(LinearGradient(colors: [Theme.accent.opacity(0.30), Theme.accent.opacity(0.14)],
                                 startPoint: .topLeading, endPoint: .bottomTrailing))
            .frame(width: size, height: size)
            .overlay(Image(systemName: symbol)
                .font(.system(size: size * 0.42, weight: .semibold))
                .foregroundStyle(Theme.accent))
    }
}

struct EntryRow: View {
    let entry: Entry
    var symbol: String = "circle.fill"
    var body: some View {
        HStack(spacing: 12) {
            if let p = entry.progress {
                ProgressRing(value: p)
            } else {
                IconDisc(symbol: symbol)
            }
            VStack(alignment: .leading, spacing: 2) {
                Text(entry.title).font(.subheadline.weight(.semibold))
                if !entry.subtitle.isEmpty {
                    Text(entry.subtitle).font(.caption).foregroundStyle(.secondary)
                }
            }
            Spacer()
            if !entry.detail.isEmpty {
                Text(entry.detail).font(.caption.weight(.semibold)).foregroundStyle(.secondary)
            }
        }
        .padding(.vertical, 2)
    }
}

/// Featured hero — one per feed, gradient with a soft accent shadow.
struct EntryCard: View {
    let entry: Entry
    var symbol: String = "sparkles"
    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            Image(systemName: symbol)
                .font(.title3.weight(.semibold))
                .foregroundStyle(.white.opacity(0.95))
                .padding(.bottom, 26)
            Text(entry.detail.uppercased())
                .font(.caption2.weight(.bold))
                .foregroundStyle(.white.opacity(0.8))
            Text(entry.title)
                .font(.title3.bold())
                .foregroundStyle(.white)
            if !entry.subtitle.isEmpty {
                Text(entry.subtitle)
                    .font(.footnote)
                    .foregroundStyle(.white.opacity(0.75))
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(16)
        .background(
            LinearGradient(colors: [Theme.accent, Theme.accent.opacity(0.55)],
                           startPoint: .topLeading, endPoint: .bottomTrailing)
        )
        .clipShape(RoundedRectangle(cornerRadius: 20))
        .shadow(color: Theme.accent.opacity(0.35), radius: 16, y: 8)
    }
}

/// Widget-style tile for grids; index 0 renders filled with the accent.
struct EntryTile: View {
    let entry: Entry
    var symbol: String = "square.grid.2x2"
    var filled: Bool = false
    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            HStack {
                if let p = entry.progress {
                    ProgressRing(value: p, size: 32)
                } else {
                    IconDisc(symbol: symbol, size: 32)
                }
                Spacer()
                Text(entry.detail)
                    .font(.caption.weight(.bold))
                    .foregroundStyle(filled ? .white.opacity(0.85) : Theme.accent)
            }
            Spacer(minLength: 14)
            Text(entry.title)
                .font(.subheadline.weight(.bold))
                .foregroundStyle(filled ? .white : .primary)
                .lineLimit(1)
            if !entry.subtitle.isEmpty {
                Text(entry.subtitle)
                    .font(.caption2)
                    .foregroundStyle(filled ? .white.opacity(0.7) : .secondary)
                    .lineLimit(1)
            }
        }
        .padding(13)
        .frame(maxWidth: .infinity, minHeight: 104, alignment: .leading)
        .background(
            filled
                ? AnyShapeStyle(LinearGradient(colors: [Theme.accent, Theme.accent.opacity(0.6)],
                                               startPoint: .topLeading, endPoint: .bottomTrailing))
                : AnyShapeStyle(Theme.surface)
        )
        .clipShape(RoundedRectangle(cornerRadius: 18))
    }
}

/// Detail push shared by every screen.
struct EntryDetailView: View {
    let entry: Entry
    let entityName: String
    var symbol: String = "sparkles"
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 14) {
                VStack(spacing: 12) {
                    if let p = entry.progress {
                        ProgressRing(value: p, size: 64)
                    } else {
                        Image(systemName: symbol)
                            .font(.system(size: 38, weight: .semibold))
                            .foregroundStyle(.white)
                    }
                    Text(entry.detail.isEmpty ? entry.title : entry.detail)
                        .font(.headline)
                        .foregroundStyle(.white)
                }
                .frame(maxWidth: .infinity)
                .padding(.vertical, 30)
                .background(
                    LinearGradient(colors: [Theme.accent, Theme.accent.opacity(0.55)],
                                   startPoint: .topLeading, endPoint: .bottomTrailing)
                )
                .clipShape(RoundedRectangle(cornerRadius: 22))
                .shadow(color: Theme.accent.opacity(0.3), radius: 18, y: 10)

                Text(entry.title).font(.title2.bold())
                if !entry.subtitle.isEmpty {
                    Text(entry.subtitle).font(.subheadline).foregroundStyle(.secondary)
                }

                VStack(spacing: 0) {
                    LabeledContent(entityName) {
                        Text(entry.detail.isEmpty ? "—" : entry.detail)
                            .foregroundStyle(Theme.accent)
                    }
                    .padding(.vertical, 10)
                    Divider()
                    LabeledContent("Status") { Text("Active") }
                        .padding(.vertical, 10)
                }
                .padding(.horizontal, 14)
                .background(Theme.surface)
                .clipShape(RoundedRectangle(cornerRadius: 14))
            }
            .padding()
        }
        .navigationTitle(entry.title)
        .navigationBarTitleDisplayMode(.inline)
    }
}
`;
}

function screenBody(tab: BlueprintTab, entity: string): string {
  const sym = tab.symbol;
  const link = (inner: string) =>
    `NavigationLink { EntryDetailView(entry: entry, entityName: "${sw(entity)}", symbol: "${sym}") } label: { ${inner} }`;
  switch (tab.kind) {
    case "feed":
      return `        ScrollView {
            ScreenHeader(headline: "${sw(tab.headline)}", subhead: "${sw(tab.subhead)}")
            LazyVStack(alignment: .leading, spacing: 12) {
                if let first = items.first {
                    NavigationLink {
                        EntryDetailView(entry: first, entityName: "${sw(entity)}", symbol: "${sym}")
                    } label: {
                        EntryCard(entry: first, symbol: "${sym}")
                    }
                    .buttonStyle(.plain)
                }
                if items.count > 1 {
                    Text("UP NEXT")
                        .font(.caption2.weight(.bold))
                        .foregroundStyle(.secondary)
                        .padding(.top, 6)
                    VStack(spacing: 0) {
                        ForEach(items.dropFirst()) { entry in
                            ${link(`EntryRow(entry: entry, symbol: "${sym}")`)}
                            .buttonStyle(.plain)
                            .padding(.vertical, 6)
                            if entry.id != items.last?.id { Divider() }
                        }
                    }
                    .padding(.horizontal, 14)
                    .padding(.vertical, 4)
                    .background(Theme.surface)
                    .clipShape(RoundedRectangle(cornerRadius: 16))
                }
            }
            .padding()
        }`;
    case "grid":
      return `        ScrollView {
            ScreenHeader(headline: "${sw(tab.headline)}", subhead: "${sw(tab.subhead)}")
            LazyVGrid(columns: [GridItem(.flexible(), spacing: 11), GridItem(.flexible(), spacing: 11)], spacing: 11) {
                ForEach(Array(items.enumerated()), id: \\.element.id) { index, entry in
                    NavigationLink {
                        EntryDetailView(entry: entry, entityName: "${sw(entity)}", symbol: "${sym}")
                    } label: {
                        EntryTile(entry: entry, symbol: "${sym}", filled: index == 0)
                    }
                    .buttonStyle(.plain)
                }
            }
            .padding()
        }`;
    case "form":
      return `        Form {
            Section {
                TextField("Title", text: $draftTitle)
                TextField("Notes", text: $draftNotes, axis: .vertical)
                    .lineLimit(3, reservesSpace: true)
            }
            Section {
                Button {
                    // demo action
                } label: {
                    Text("Add").font(.headline).frame(maxWidth: .infinity)
                }
                .buttonStyle(.borderedProminent)
                .tint(Theme.accent)
                .listRowInsets(EdgeInsets())
                .listRowBackground(Color.clear)
            }
            Section("Recent") {
                ForEach(items) { entry in
                    ${link(`EntryRow(entry: entry, symbol: "${sym}")`)}
                }
            }
        }`;
    case "profile":
      return `        List {
            Section {
                VStack(spacing: 6) {
                    Circle()
                        .fill(LinearGradient(colors: [Theme.accent, Theme.accent.opacity(0.55)],
                                             startPoint: .topLeading, endPoint: .bottomTrailing))
                        .frame(width: 84, height: 84)
                        .overlay(Image(systemName: "person.fill").font(.largeTitle).foregroundStyle(.white))
                    Text("${sw(tab.headline)}").font(.title3.bold())
                    Text("${sw(tab.subhead)}").font(.footnote).foregroundStyle(.secondary)
                }
                .frame(maxWidth: .infinity)
                .listRowBackground(Color.clear)
            }
            Section {
                ForEach(items) { entry in
                    ${link(`EntryRow(entry: entry, symbol: "${sym}")`)}
                }
            }
        }`;
    default: // list
      return `        List {
            Section {
                ForEach(items) { entry in
                    ${link(`EntryRow(entry: entry, symbol: "${sym}")`)}
                }
            } header: {
                if !"${sw(tab.subhead)}".isEmpty {
                    Text("${sw(tab.subhead)}").textCase(nil).font(.footnote)
                }
            }
        }
            .listStyle(.insetGrouped)`;
  }
}

function screenSwift(tab: BlueprintTab, i: number, typeName: string, entity: string): string {
  const needsFormState = tab.kind === "form";
  const state = needsFormState
    ? `    @State private var draftTitle = ""\n    @State private var draftNotes = ""\n`
    : "";
  const titleMode = tab.kind === "list" || tab.kind === "form" || tab.kind === "profile" ? "large" : "inline";
  return `import SwiftUI

struct ${typeName}: View {
    private let items = SampleData.tab${i}
${state}
    var body: some View {
        NavigationStack {
${screenBody(tab, entity)}
                .navigationTitle("${sw(tab.title)}")
                .navigationBarTitleDisplayMode(.${titleMode})
        }
    }
}
`;
}

function rootViewSwift(b: AppBlueprint, typeNames: string[]): string {
  const tabs = b.tabs
    .map(
      (tab, i) => `            ${typeNames[i]}()
                .tabItem { Label("${sw(tab.title)}", systemImage: "${tab.symbol}") }`,
    )
    .join("\n");
  return `import SwiftUI

struct RootView: View {
    var body: some View {
        TabView {
${tabs}
        }
        .tint(Theme.accent)
    }
}
`;
}

function appSwift(b: AppBlueprint, projectName: string): string {
  return `import SwiftUI

// ${b.appName} — ${b.tagline}
// A clone scaffold generated by the Kittie iOS Clone Engine.
@main
struct ${projectName}App: App {
    var body: some Scene {
        WindowGroup {
            RootView()
        }
    }
}
`;
}

function readme(b: AppBlueprint, projectName: string): string {
  return `# ${b.appName}

> ${b.tagline}

Generated by the **Kittie iOS Clone Engine** — a SwiftUI clone scaffold of a
trending App Store app. Core entity: **${b.primaryEntity}**.

## Screens
${b.tabs.map((t) => `- **${t.title}** (${t.kind}) — ${t.headline}`).join("\n")}

## Build & run

\`\`\`sh
xcodegen generate
open ${projectName}.xcodeproj
# or, headless on a booted simulator:
xcodebuild -project ${projectName}.xcodeproj -scheme ${projectName} \\
  -destination 'generic/platform=iOS Simulator' build
\`\`\`

Accent color: \`${b.accentHex}\`.  Bundle id: \`${b.bundleId}\`.
`;
}

/** Render a validated blueprint into a complete xcodegen project. */
export function generateProject(b: AppBlueprint): { projectName: string; files: GeneratedFile[] } {
  const projectName = projectNameFor(b);
  const typeNames = b.tabs.map((t, i) => tabTypeName(t, i));
  const files: GeneratedFile[] = [
    { path: "project.yml", contents: projectYml(b, projectName) },
    { path: "README.md", contents: readme(b, projectName) },
    { path: "Sources/App.swift", contents: appSwift(b, projectName) },
    { path: "Sources/Theme.swift", contents: themeSwift(b) },
    { path: "Sources/Components.swift", contents: componentsSwift() },
    { path: "Sources/Models.swift", contents: modelSwift(b) },
    { path: "Sources/RootView.swift", contents: rootViewSwift(b, typeNames) },
    ...b.tabs.map((tab, i) => {
      const tn = typeNames[i] ?? tabTypeName(tab, i);
      return { path: `Sources/${tn}.swift`, contents: screenSwift(tab, i, tn, b.primaryEntity) };
    }),
  ];
  return { projectName, files };
}

/* ---- real .xcodeproj emission ------------------------------------------- */

/* Xcode 16+ "synchronized folder" project: the pbxproj references the app
   folder once (PBXFileSystemSynchronizedRootGroup) and Xcode discovers the
   Swift files inside it, so no per-file build entries are needed and the
   project can never drift out of sync with the generated sources. */

const OID = (n: number) => `KA10000000000000000000${n.toString(16).toUpperCase().padStart(2, "0")}`;

function pbxproj(projectName: string, bundleId: string): string {
  const [grp, app, fwk, root, products, target, tcl, src, res, proj, pcl, dbgP, relP, dbgT, relT] =
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15].map(OID);
  return `// !$*UTF8*$!
{
	archiveVersion = 1;
	classes = {
	};
	objectVersion = 77;
	objects = {

/* Begin PBXFileReference section */
		${app} /* ${projectName}.app */ = {isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = ${projectName}.app; sourceTree = BUILT_PRODUCTS_DIR; };
/* End PBXFileReference section */

/* Begin PBXFileSystemSynchronizedRootGroup section */
		${grp} /* ${projectName} */ = {isa = PBXFileSystemSynchronizedRootGroup; explicitFileTypes = {}; explicitFolders = (); path = ${projectName}; sourceTree = "<group>"; };
/* End PBXFileSystemSynchronizedRootGroup section */

/* Begin PBXFrameworksBuildPhase section */
		${fwk} /* Frameworks */ = {
			isa = PBXFrameworksBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXFrameworksBuildPhase section */

/* Begin PBXGroup section */
		${root} = {
			isa = PBXGroup;
			children = (
				${grp} /* ${projectName} */,
				${products} /* Products */,
			);
			sourceTree = "<group>";
		};
		${products} /* Products */ = {
			isa = PBXGroup;
			children = (
				${app} /* ${projectName}.app */,
			);
			name = Products;
			sourceTree = "<group>";
		};
/* End PBXGroup section */

/* Begin PBXNativeTarget section */
		${target} /* ${projectName} */ = {
			isa = PBXNativeTarget;
			buildConfigurationList = ${tcl} /* Build configuration list for PBXNativeTarget "${projectName}" */;
			buildPhases = (
				${src} /* Sources */,
				${fwk} /* Frameworks */,
				${res} /* Resources */,
			);
			buildRules = (
			);
			dependencies = (
			);
			fileSystemSynchronizedGroups = (
				${grp} /* ${projectName} */,
			);
			name = ${projectName};
			packageProductDependencies = (
			);
			productName = ${projectName};
			productReference = ${app} /* ${projectName}.app */;
			productType = "com.apple.product-type.application";
		};
/* End PBXNativeTarget section */

/* Begin PBXProject section */
		${proj} /* Project object */ = {
			isa = PBXProject;
			attributes = {
				BuildIndependentTargetsInParallel = 1;
				LastSwiftUpdateCheck = 1600;
				LastUpgradeCheck = 1600;
				TargetAttributes = {
					${target} = {
						CreatedOnToolsVersion = 16.0;
					};
				};
			};
			buildConfigurationList = ${pcl} /* Build configuration list for PBXProject "${projectName}" */;
			developmentRegion = en;
			hasScannedForEncodings = 0;
			knownRegions = (
				en,
				Base,
			);
			mainGroup = ${root};
			minimizedProjectReferenceProxies = 1;
			preferredProjectObjectVersion = 77;
			productRefGroup = ${products} /* Products */;
			projectDirPath = "";
			projectRoot = "";
			targets = (
				${target} /* ${projectName} */,
			);
		};
/* End PBXProject section */

/* Begin PBXResourcesBuildPhase section */
		${res} /* Resources */ = {
			isa = PBXResourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXResourcesBuildPhase section */

/* Begin PBXSourcesBuildPhase section */
		${src} /* Sources */ = {
			isa = PBXSourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXSourcesBuildPhase section */

/* Begin XCBuildConfiguration section */
		${dbgP} /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ALWAYS_SEARCH_USER_PATHS = NO;
				CLANG_ANALYZER_NONNULL = YES;
				CLANG_ENABLE_MODULES = YES;
				CLANG_ENABLE_OBJC_ARC = YES;
				COPY_PHASE_STRIP = NO;
				DEBUG_INFORMATION_FORMAT = dwarf;
				ENABLE_STRICT_OBJC_MSGSEND = YES;
				ENABLE_TESTABILITY = YES;
				GCC_DYNAMIC_NO_PIC = NO;
				GCC_OPTIMIZATION_LEVEL = 0;
				GCC_PREPROCESSOR_DEFINITIONS = (
					"DEBUG=1",
					"$(inherited)",
				);
				IPHONEOS_DEPLOYMENT_TARGET = 17.0;
				MTL_ENABLE_DEBUG_INFO = INCLUDE_SOURCE;
				MTL_FAST_MATH = YES;
				ONLY_ACTIVE_ARCH = YES;
				SDKROOT = iphoneos;
				SWIFT_ACTIVE_COMPILATION_CONDITIONS = "DEBUG $(inherited)";
				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
			};
			name = Debug;
		};
		${relP} /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ALWAYS_SEARCH_USER_PATHS = NO;
				CLANG_ANALYZER_NONNULL = YES;
				CLANG_ENABLE_MODULES = YES;
				CLANG_ENABLE_OBJC_ARC = YES;
				COPY_PHASE_STRIP = NO;
				DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
				ENABLE_NS_ASSERTIONS = NO;
				ENABLE_STRICT_OBJC_MSGSEND = YES;
				IPHONEOS_DEPLOYMENT_TARGET = 17.0;
				MTL_ENABLE_DEBUG_INFO = NO;
				MTL_FAST_MATH = YES;
				SDKROOT = iphoneos;
				SWIFT_COMPILATION_MODE = wholemodule;
				VALIDATE_PRODUCT = YES;
			};
			name = Release;
		};
		${dbgT} /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				CODE_SIGN_STYLE = Automatic;
				CURRENT_PROJECT_VERSION = 1;
				ENABLE_PREVIEWS = YES;
				GENERATE_INFOPLIST_FILE = YES;
				INFOPLIST_KEY_UIApplicationSceneManifest_Generation = YES;
				INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents = YES;
				INFOPLIST_KEY_UILaunchScreen_Generation = YES;
				INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone = UIInterfaceOrientationPortrait;
				LD_RUNPATH_SEARCH_PATHS = (
					"$(inherited)",
					"@executable_path/Frameworks",
				);
				MARKETING_VERSION = 1.0;
				PRODUCT_BUNDLE_IDENTIFIER = ${bundleId};
				PRODUCT_NAME = "$(TARGET_NAME)";
				SWIFT_EMIT_LOC_STRINGS = YES;
				SWIFT_VERSION = 5.0;
				TARGETED_DEVICE_FAMILY = 1;
			};
			name = Debug;
		};
		${relT} /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				CODE_SIGN_STYLE = Automatic;
				CURRENT_PROJECT_VERSION = 1;
				ENABLE_PREVIEWS = YES;
				GENERATE_INFOPLIST_FILE = YES;
				INFOPLIST_KEY_UIApplicationSceneManifest_Generation = YES;
				INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents = YES;
				INFOPLIST_KEY_UILaunchScreen_Generation = YES;
				INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone = UIInterfaceOrientationPortrait;
				LD_RUNPATH_SEARCH_PATHS = (
					"$(inherited)",
					"@executable_path/Frameworks",
				);
				MARKETING_VERSION = 1.0;
				PRODUCT_BUNDLE_IDENTIFIER = ${bundleId};
				PRODUCT_NAME = "$(TARGET_NAME)";
				SWIFT_EMIT_LOC_STRINGS = YES;
				SWIFT_VERSION = 5.0;
				TARGETED_DEVICE_FAMILY = 1;
			};
			name = Release;
		};
/* End XCBuildConfiguration section */

/* Begin XCConfigurationList section */
		${pcl} /* Build configuration list for PBXProject "${projectName}" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				${dbgP} /* Debug */,
				${relP} /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
		${tcl} /* Build configuration list for PBXNativeTarget "${projectName}" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				${dbgT} /* Debug */,
				${relT} /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
/* End XCConfigurationList section */
	};
	rootObject = ${proj} /* Project object */;
}
`;
}

function xcodeReadme(b: AppBlueprint, projectName: string): string {
  return `# ${b.appName}

> ${b.tagline}

A native SwiftUI app generated by the **Kittie Builder**. Core entity:
**${b.primaryEntity}** · accent \`${b.accentHex}\` · bundle id \`${b.bundleId}\`.

## Screens
${b.tabs.map((t) => `- **${t.title}** (${t.kind}) — ${t.headline}`).join("\n")}

## Build & run

\`\`\`sh
open ${projectName}.xcodeproj
# or headless:
xcodebuild -project ${projectName}.xcodeproj -scheme ${projectName} \\
  -destination 'generic/platform=iOS Simulator' build CODE_SIGNING_ALLOWED=NO
\`\`\`
`;
}

/** Render a validated blueprint into a ready-to-open Xcode project (no xcodegen). */
export function generateXcodeProject(b: AppBlueprint): { projectName: string; files: GeneratedFile[] } {
  const projectName = projectNameFor(b);
  const typeNames = b.tabs.map((t, i) => tabTypeName(t, i));
  const files: GeneratedFile[] = [
    { path: `${projectName}.xcodeproj/project.pbxproj`, contents: pbxproj(projectName, b.bundleId) },
    { path: "README.md", contents: xcodeReadme(b, projectName) },
    { path: `${projectName}/App.swift`, contents: appSwift(b, projectName) },
    { path: `${projectName}/Theme.swift`, contents: themeSwift(b) },
    { path: `${projectName}/Components.swift`, contents: componentsSwift() },
    { path: `${projectName}/Models.swift`, contents: modelSwift(b) },
    { path: `${projectName}/RootView.swift`, contents: rootViewSwift(b, typeNames) },
    ...b.tabs.map((tab, i) => {
      const tn = typeNames[i] ?? tabTypeName(tab, i);
      return { path: `${projectName}/${tn}.swift`, contents: screenSwift(tab, i, tn, b.primaryEntity) };
    }),
  ];
  return { projectName, files };
}
